//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserSignupLogin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBuserSignupLoginEntities2 : DbContext
    {
        public DBuserSignupLoginEntities2()
            : base("name=DBuserSignupLoginEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StudentDetail> StudentDetails { get; set; }
        public virtual DbSet<TBLUserInfo> TBLUserInfoes { get; set; }
        public virtual DbSet<SubjectDetail> SubjectDetails { get; set; }
    }
}
