//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserSignupLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLUserInfo
    {
        //internal object UserUS;
        //internal object PasswordUS;

        public int IdUs { get; set; }

        //[Required(ErrorMessage = "This field is required")]
        //[Display(Name = "Username")]

        public string UserUs { get; set; }
       // public object UserUS { get; internal set; }

        //[DataType(DataType.Password)]
        //[Required(ErrorMessage = "This field is required")]
        //[Display(Name = "Password")]
        public string PasswordUs { get; set; }
       // public object PasswordUS { get; internal set; }

        //[DataType(DataType.Password)]
        //[Required(ErrorMessage = "This field is required")]
        //[Display(Name = "RePassword")]
        //[Compare("Passwordus",ErrorMessage = "Confirm password doesn't match")]
        public string RePasswordUs { get; set; }

    }
}
